# Generated by Django 5.1.5 on 2025-03-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=140)),
                ('address2', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('tiruchirappalli', 'Tiruchirappalli'), ('salem', 'Salem'), ('tirunelveli', 'Tirunelveli'), ('vellore', 'Vellore'), ('thoothukudi', 'Thoothukudi'), ('kancheepuram', 'Kancheepuram'), ('erode', 'Erode'), ('karur', 'Karur'), ('dharmapuri', 'Dharmapuri'), ('thanjavur', 'Thanjavur'), ('virudhunagar', 'Virudhunagar'), ('nagapattinam', 'Nagapattinam'), ('rameswaram', 'Rameswaram'), ('kanyakumari', 'Kanyakumari'), ('krishnagiri', 'Krishnagiri'), ('tiruvarur', 'Tiruvarur'), ('cuddalore', 'Cuddalore'), ('pudukkottai', 'Pudukkottai')], max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
