# Generated by Django 5.1.5 on 2025-03-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('tiruchirappalli', 'Tiruchirappalli'), ('salem', 'Salem'), ('tirunelveli', 'Tirunelveli'), ('vellore', 'Vellore'), ('thoothukudi', 'Thoothukudi'), ('kancheepuram', 'Kancheepuram'), ('erode', 'Erode'), ('karur', 'Karur'), ('dharmapuri', 'Dharmapuri'), ('thanjavur', 'Thanjavur'), ('virudhunagar', 'Virudhunagar'), ('nagapattinam', 'Nagapattinam'), ('rameswaram', 'Rameswaram'), ('kanyakumari', 'Kanyakumari'), ('krishnagiri', 'Krishnagiri'), ('tiruvarur', 'Tiruvarur'), ('cuddalore', 'Cuddalore'), ('pudukkottai', 'Pudukkottai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50),
        ),
    ]
