# Generated by Django 5.1.5 on 2025-05-14 06:08

import django.db.models.deletion
import main.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_location_city_alter_location_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple'), ('xiaomi', 'Xiaomi'), ('realme', 'Realme'), ('vivo', 'Vivo'), ('oppo', 'Oppo'), ('oneplus', 'OnePlus'), ('motorola', 'Motorola'), ('iqoo', 'iQOO'), ('google', 'Google'), ('nothing', 'Nothing'), ('lava', 'Lava'), ('infinix', 'Infinix'), ('tecno', 'Tecno'), ('nokia', 'Nokia'), ('asus', 'Asus')], max_length=24)),
                ('ram', models.CharField(choices=[('4gb', '4GB'), ('6gb', '6GB'), ('8gb', '8GB')], max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
